[workspace]
authors = ["John McLevey <john.mclevey@hey.com>"]
channels = ["conda-forge"]
name = "black-book-talks"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
preview = { cmd = "cd docs/ && python -m http.server 8080" }

update-blog = { cmd = "python scripts/build_blog.py" }
update-cv = { cmd = "python scripts/build_cv.py" }


[dependencies]
openai = ">=2.16.0,<3"
python = ">=3.11,<3.13"
ipykernel = ">=6.30.1,<7"
jupyter = ">=1.1.1,<2"
pandas = { version = ">=2.3.1,<3", channel = "conda-forge" }
pip = ">=25.2,<26"
pyyaml = { version = ">=6.0.2,<7", channel = "conda-forge" }
markdown = { version = ">=3.5,<4", channel = "conda-forge" }
graphviz = { version = ">=11,<13", channel = "conda-forge" }
python-graphviz = { version = ">=0.20,<1", channel = "conda-forge" }
